### ISSUE TITLE
Class Kodilab\LaravelI18n\I18n does not exist

### ISSUE THREAD

**Issue by poratuk** [jurios/laravel-i18n#5]
After full installation: 
1. 
`php artisan vendor:publish --provider="Kodilab\LaravelFilters\QueryFilterProvider"` not add config filters.php. 
2. When I add 
`i18n:routes();`
have critical issue `ReflectionException (-1)
Class Kodilab\LaravelI18n\I18n does not exist` 
Checked your plugin. Have only: `I18nProvider` Class. 
add `I18nProvider:routes();` give another critical error

**Comment by jurios** [comment]
Hi @poratuk ,

unfortunately, this package is still WIP as I detected some limitations that I need to solve (sorry I will add a notice in the `README.md` file, my fault). As you can see, there is a `v3` branch where I am working on. 

Let me explain the limitations. Laravel has some places where it uses its own localization system. For example, validation uses the laravel localization internally in order to show the error messages. If you have a fresh laravel installation you can see all of them in the `resources/lang/en` folder. As it uses the Laravel localization system, those message are "invisible" for the `larave-i18n` package.
The same will happen with 3th-party packages which publish translations.

That's why I am not happy with the solution. It's not extensible and this has to be fixed.

I am working on another solution (v3) which is full-integrated with the Laravel localization system thus you could define the translations for laravel and 3th-party packages texts  using the editor for each `locale` defined. Unfortunately, it's still WIP. I would like to finish it as soon as possible. I let you know when it is usable.

Again, sorry for the inconvenience.

**Comment by jurios** [comment]
Hi @poratuk ,

I redesigned the package and now is using the `laravel` localization system under the hood. This redesign fixes the problems explained in the previous comment. Hopefully, the bugs you described  has been fixed too. I released this version with the tag `v1.0.0`.

If you want to use this new version, `README` file has been updated with the steps to use it.

As it has been completely redesigned, this issue can be closed. 

Please, if you find out another error, don't hesitate to create another issue.

Thanks.
